comprobantes_all:
    path: /
    defaults: { _controller: BackendBundle:Comprobantes:all }
    methods: GET

comprobantes_tipos:
    path: /tipos
    defaults: { _controller: BackendBundle:Comprobantes:tipos }
    methods: GET

comprobantes_newtipo:
    path: /newtipo
    defaults: { _controller: BackendBundle:Comprobantes:newtipo }
    methods: POST

comprobantes_newcomp:
    path: /newcomp
    defaults: { _controller: BackendBundle:Comprobantes:newcomp }
    methods: POST

comprobantes_editcomp:
    path: /{id}/editcomp
    defaults: { _controller: BackendBundle:Comprobantes:editcomp }
    methods: POST

comprobantes_edittipo:
    path: /{id}/edittipo
    defaults: { _controller: BackendBundle:Comprobantes:edittipo }
    methods: POST