ventas_all:
    path: /{id}
    defaults: { _controller: BackendBundle:Ventas:all }
    methods: GET

ventas_new:
    path: /{id}/new
    defaults: { _controller: BackendBundle:Ventas:new }
    methods: POST

ventas_update:
    path: /{id}/update
    defaults: { _controller: BackendBundle:Ventas:update }
    methods: POST

ventas_del:
    path: /{id}/del
    defaults: { _controller: BackendBundle:Ventas:del }
    methods: POST

