# Pantalla general de todos los informes.
informes_index:
  path: /
  defaults: { _controller: "FrontendBundle:Modulos:informes" }
  methods: GET

# Informes de ventas - Por fechas
informes_ventas_por_fecha:
  path: /ventas-por-fecha/{id}
  defaults: { _controller: "FrontendBundle:Informes:ventasPorFecha" }
  methods: GET

# Informes de ventas - Por periodo
informes_ventas_por_periodo:
  path: /ventas-por-periodo/{id}
  defaults: { _controller: "FrontendBundle:Informes:ventasPorPeriodo" }
  methods: GET

# Informes de ventas - Por jurisdiccion
informes_ventas_por_jurisdiccion:
  path: /ventas-por-jurisdiccion/{id}
  defaults: { _controller: "FrontendBundle:Informes:ventasPorJurisdiccion" }
  methods: GET

# Informes de ventas - Por cliente
informes_ventas_por_cliente:
  path: /ventas-por-cliente/{id}
  defaults: { _controller: "FrontendBundle:Informes:ventasPorCliente" }
  methods: GET

# Informes de ventas - Por comprobante
informes_ventas_por_comprobante:
  path: /ventas-por-comprobante/{id}
  defaults: { _controller: "FrontendBundle:Informes:ventasPorComprobante" }
  methods: GET

#### FALTAN POR HACER ####

## IMPORTANTE!!: SIEMPRE VOY A RECIBIR UN ID DENTRO DEL INFORME - VER COMO RECIBIRLO COMO PARAMETRO.

# Ventas por cliente - Tooltip con checks para todas los clientes.

# Ventas por comprobante - Tooltip con checks para todos los comprobantes
