frontend_default:
  resource: "@FrontendBundle/Resources/config/routing/default.yml"
  prefix: /

frontend_prueba:
  resource: "@FrontendBundle/Resources/config/routing/prueba.yml"
  prefix: /prueba

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fontend_home:
    resource: "@FrontendBundle/Resources/config/routing/home.yml"
    prefix: /home    

frontend_contable:
    resource: "@FrontendBundle/Resources/config/routing/contable.yml"
    prefix: /contable    

frontend_impositivo:
    resource: "@FrontendBundle/Resources/config/routing/impositivo.yml"
    prefix: /impositivo 

frontend_configuraciones:
    resource: "@FrontendBundle/Resources/config/routing/configuraciones.yml"
    prefix: /configuraciones
