backend_homepage:
    path: /
    defaults: { _controller: BackendBundle:Default:index }

backend_default:
  resource: "@BackendBundle/Resources/config/routing/default.yml"
  prefix: /

backend_user:
  resource: "@BackendBundle/Resources/config/routing/user.yml"
  prefix: /user

backend_empresas:
  resource: "@BackendBundle/Resources/config/routing/empresas.yml"
  prefix: /empresa

backend_razonessociales:
  resource: "@BackendBundle/Resources/config/routing/razonessociales.yml"
  prefix: /razonsocial

backend_compras:
  resource: "@BackendBundle/Resources/config/routing/compras.yml"
  prefix: /contable/compras

backend_ventas:
  resource: "@BackendBundle/Resources/config/routing/ventas.yml"
  prefix: /contable/ventas

backend_rubros:
  resource: "@BackendBundle/Resources/config/routing/rubros.yml"
  prefix: /rubros

backend_provincias:
  resource: "@BackendBundle/Resources/config/routing/provincias.yml"
  prefix: /provincias

backend_jurisdicciones:
  resource: "@BackendBundle/Resources/config/routing/jurisdicciones.yml"
  prefix: /jurisdicciones

backend_comprobantes:
  resource: "@BackendBundle/Resources/config/routing/comprobantes.yml"
  prefix: /comprobantes

backend_proveedores:
  resource: "@BackendBundle/Resources/config/routing/proveedores.yml"
  prefix: /proveedores

backend_imputaciones:
  resource: "@BackendBundle/Resources/config/routing/imputaciones.yml"
  prefix: /imputaciones

backend_impositivo_iva:
  resource: "@BackendBundle/Resources/config/routing/iva.yml"
  prefix: /impositivo/iva

backend_impositivo_iibb:
  resource: "@BackendBundle/Resources/config/routing/iibb.yml"
  prefix: /impositivo/iibb

backend_iva:
  resource: "@BackendBundle/Resources/config/routing/tiposIva.yml"
  prefix: /iva

backend_tiposiibb:
  resource: "@BackendBundle/Resources/config/routing/tiposIibb.yml"
  prefix: /iibb